import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import Layout from '@/components/layout/layout'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const roboto = Roboto({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Layout>{children}</Layout>
        <Toaster />
      </body>
    </html>
  );
}
