import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import Layout from '@/components/layout/layout'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import {Suspense} from "react";

const roboto = Roboto({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Suspense fallback={
          <div className="min-h-screen flex items-center justify-center">
            <span className="loading loading-spinner loading-sm"></span>
          </div>
        }>
          <Layout>{children}</Layout>
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
